language: python
python:
  - 3.7

before_install:
  - pip install codecov

install:
  - pip install ".[test]"

script:
  - coverage run --source=textory -m pytest

after_success:
  - codecov

deploy:
  - provider: pypi
    user: BENR0
    password:
      secure: s+IPws7jO2QN+bgKqm4ui9J68jqsG2ClGFzTOHUDKxWSQgl54ixnoODzuiYUlJJxhSP5tDZlz9oaAckq9rb1zhaPjdNHRh+Hwy/loLmnnDdHUBDkbNSFs6nqJvwYfS5AN8x92ZEpCekUg9KgsTa2skAPEXGxK4luJct3hyZe4DTuoazevjiNfeCdzk49uHq/ay4S51a7mJ83JerUk4WNyTyIZXfVn2nsHwBDx8Gl64kiiaRRMTMWbgUGELJMarBsYDZKF2ynpZtMi+dq9UlqhW3jtSoiHHEZxbZ/q1FT9Dbyr1kO95SGzfys7FKCa+DYAnPVNTFgvqgSkDGpjDqlstIk3ZRGRo38VHp0Y810JMLnPWQIWjE6c6SrEExNgFbYsdxhtA4tED4ab8LFm648cxQEOhtW6XRraCxW6LfRj6Iorj7FIWo2uUFyDmwIVBDxUG87QcZtShgyHcOlErdAeOUR4rqNI+TMFTlaGpxccbiAP2joHizs3mIazifelfDRQMKsJAdQN6E041s2eHjzYwBsFLAEETiMYZMdwwIvmjEWRsaNW043SwOyn6BC59xdw5SN/L8I3QeHygKxDXaNMkg9fSfhF2v/jTAYvniujs36+izndqybkBhZ0tyOfO1byggyR4fo0uDBNFAkKAIeWHRPjYuJjD+l9fipbh3+Nls=
    distributions: sdist
    skip_existing: true
    on:
      tags: true

notifications:
  slack:
    secure: iekdJgN8RHeYXPGivQVINaBXi4nDk3lVSGzLhA5tphRhRcF/JOjrz3JJiR6uPIWVsnqWnQMUbrAWw8FklH2Zk+uXBgxuZ+mCSSlHFdOKxAB7UZS7slsL1dtURck1N9I/73W8A263mtOz1oEla/zL/TP6s+DdwnxKM13ocglGA3pZEtaFxXRDtcajBYBWmMpoc00cInQSmZWMTX0jdRT+VVLBvWkDIvw8TwEtLxIW2C88eAWZYONY7u+VEXJpZG9QQ2xQMG4ddsHApvYpupRogF1W+HHiq/2tSSj6gCjjfW4Ao4vBGOdm+sH1u3ihEGd7KYXjYKFF4eLmPFXoviaWUjnuF6NsIy26zjFET50AqlF7u88es4TvsW9R+rfotvg1lwRbZo++OBXv9VAcdpe8fZevid77+8SLO5WBthjBuWqx6rKzk1TnJVQsYfQ7hOFxH6ZJE7m7paGHgfpgH2aQuVkicSCU39FrWiAVGmF0aQvFv2LWP/ozdNVJsC/e7s4+SxMybKMEStDm/DYOlpewFIHPTEYJaZLiEGROKpl314P5bqVgiTlQb2T8JcZjry/bg2R3IYD6HKvh6d59A7D5Cp8AP7jkOhW3WSr/bbJi43okYuVHmucKqO9QmZadG+Gdi9Pz61I2JkzqbygP37r9rs3AhEqXy6XsGRar8q4s7z0=
  on_success: never
  on_failure: always
